version: '3.3'

services:
    web:
        environment:
            BRANCH: master
            SYMFONY_VERSION: 4.4
            PR_ORIGIN: whatever
        network_mode: host
        build: .
        volumes:
            - .:/code
            - /var/run/docker.sock:/var/run/docker.sock
